import { getAllPosts } from "lib/api"
import Head from 'next/head'

import Hero from "@/components/hero"
import Container from '@/components/container'
import Posts from "@/components/posts"
import { eyecatchLocal } from "@/lib/constants"
import { getPlaiceholder } from "plaiceholder"
import Pagination from "@/components/pagination"
import type { Post } from "@/types/types"

export default function Home({ posts }: { posts: Post[] }) {
  return (
    <>
      <Head>
        <title>Diary</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Hero
          title="HOME"
          subtitle="放送大学での勉強に関する日記です。"
          imageOn
        />

        <Posts posts={posts} />

        <Pagination nextUrl="/blog" nextText="More Posts" />
      </Container>
    </>
  )
}

export async function getStaticProps() {
  const posts = await getAllPosts(4)

  for (const post of posts) {
    if (!post.hasOwnProperty("eyecatch")) {
      post.eyecatch = eyecatchLocal
    }

    const { base64 } = await getPlaiceholder(post.eyecatch.url)
    post.eyecatch.blurDataURL = base64
  }

  return {
    props: {
      posts: posts
    }
  }
}
