import Head from 'next/head'

import Hero from "@/components/hero"
import Container from '@/components/container'

export default function Home() {
  return (
    <>
      <Head>
        <title>Diary</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Hero
          title="HOME"
          subtitle="放送大学での勉強に関する日記です。"
          imageOn
        />
      </Container>
    </>
  )
}
